name: Build and Deploy Storybook

on:
  push:
    branches:
      - main # デプロイ元のブランチ（必要に応じて変更）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # プロジェクトに合わせた Node.js バージョン

      - name: Install Dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook
        # package.json で "build-storybook": "storybook build" などになっていることを前提

      - name: Commit and Push Storybook Build
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # docs フォルダの変更を検出してコミット
          git add docs
          git diff --cached --quiet || git commit -m "Update Storybook build"
          git push
